import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import './globals.scss'
import Navbar from "./components/Navbar"
import Footer from "./components/Footer"
import Head from 'next/head'
import logo from "../public/logo.svg"

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: "Muhammad Moyijo's portfolio",
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
        <body className={inter.className}>
            <Navbar />
            {children}
            <Footer />
        </body>
    </html>
  )
}
